### PR TITLE
Add global task timer and goal specific timer display

### PR DESCRIPTION
**Pull request by Judgy53**
Quests can have 2 different type of timers : one for the current task and one for each goal of that task. This PR allows them to be displayed.

I've made the goal specific one display before the goal description. I think it's fine, although giving it a slightly different color might look better.

However, I didn't find a good place to display the current task one. I've put it next to the tier completion in the default format (like this : ``[L50] [1/5] [03:50]``). It's not really visible and should probably be changed, but at least, the feature is here.

Here's a few quests I used to test out those timers :

```
Task timer :
	- The Chrome Steed 1/4 : Ricky Pagan (Kaidan)
	- Dead Rising 4/4 : Moutnefert (City of the Sun God)
Goal timer :
	- Fungal Fireworks 5/5 : Luminita (Shadowy Forest)
	- Digging too deep 1/5 : Moutemouia (City of the Sun God)
	- Mummy Massacre 1/1 : Blood-covered Blade (City of the Sun God)
```

### CODE REVIEW

**Comment by infidel-** [comment]
Thanks! I'll check it out.

What do you mean by "It's not really visible"?

**Comment by Judgy53** [comment]
> What do you mean by "It's not really visible"? 

The task timer look like this : https://i.imgur.com/qXGePDx.png
While the goal one looks like this : https://i.imgur.com/N3dt7Wr.png

I think the goal timer stands out just fine, while the task one looks like optional information. My point was it should be displayed somewhere else, or in another color maybe.

Something I forgot to mention is that it relies on the setInterval redraw, which means it often skips 1 second. Increasing the throttle speed might be something to consider.

**Comment by infidel-** [comment]
> I think the goal timer stands out just fine, while the task one looks like optional information. My point was it should be displayed somewhere else, or in another color maybe.

I think the best way is to make it bold, red and in front of the mission name since it's important. Or the same in front of goal text. Want me to do it?

> Something I forgot to mention is that it relies on the setInterval redraw, which means it often skips 1 second. Increasing the throttle speed might be something to consider.

I'll lower it to 500ms, that should help and still be reasonably light on performance.

**Comment by Judgy53** [comment]
> I think the best way is to make it bold, red and in front of the mission name since it's important. Or the same in front of goal text. Want me to do it?

Just did it, and also changed the color of the timer goal a tiny bit.
Task Timer : https://i.imgur.com/qV0U1Df.png
Goal Timer : https://i.imgur.com/JXU7GL3.png

**Comment by infidel-** [comment]
Looks great. I'll check it out ingame later today.

**Comment by infidel-** [comment]
Thanks for the submissions! I'll work on one more feature and release soon if you don't have anything else in the pipeline.

**Comment by infidel-** [comment]
Weirdly enough, lowering the redraw timer does not do anything, it's just that `Utils.GetServerSyncedTime()` always updates once per 2 seconds. While the same code works fine in the original mission timer. And we can't use the local alternative `Date.getTime()` since it differs with server time (34 seconds in my case). I'll leave it that way and mention that somewhere in the addon notes.

**Pull request merged**
